### ISSUE TITLE
admin/assignment/unassigned:

### ISSUE THREAD

**Issue by thiagobardini** [codeforboston/urban-league-heat-pump-accelerator#397] opened 2023-06-14 14:07 UTC
DO NOT include public survey created homes on this page

**Comment by LWest001** [comment] 2023-06-23 18:08
I've been working on this, but the result is a quite convoluted join of `/survey_visits?surveyor_id` (publicly created survey visits) and `/homes?assignment_id` (unassigned homes). Basically, have to load unassigned homes data, then filter that data through publicly created survey visits, returning only unassigned homes that do not belong to any publicly created survey visits.

Here's the useEffect that accomplishes all of that:
```
  useEffect(() => {
    if (
      isUnassignedHomesDataLoading ||
      isPublicSurveyVisitsDataLoading ||
      unassignedNonpublicHomes.length
    )
      return;
    const filteredHomes = unassignedHomesData.filter((home) =>
      publicSurveyVisitsData.find(
        (surveyVisit) => surveyVisit.home_id !== home.id
      )
    );
    setUnassignedNonpublicHomes(filteredHomes);
  }, [
    isUnassignedHomesDataLoading,
    isPublicSurveyVisitsDataLoading,
    unassignedHomesData,
    publicSurveyVisitsData,
    unassignedNonpublicHomes,
  ]);
```

I don't think this scales well (time complexity O(mn) anyone?). A better solution would probably be to attach a `creator` property when creating homes that could be either `:user` or `public`.

**Comment by mikelynch** [comment] 2023-06-23 19:14
@LWest001 , what are you trying to achieve here with this join?

**Comment by LWest001** [comment] 2023-06-23 19:22
There is an Unassigned page for admins to see homes that have been created but not put on an assignment. From there they can add a home to an assignment. The issue is that homes created via the public survey are technically not on an assignment, but they don't belong on an assignment either because publicly created homes = homes that have completed a survey online already.

So we want a table that shows homes that have been created internally (ie need to be surveyed) but have not been added to an assignment yet.

**Comment by mikelynch** [comment] 2023-06-23 19:28
I don't think it's merged in yet, but we're adding two attributes to homes (see #405 ) that will show whether they've ever been visited (i.e. have an associated survey_visit) or if they're completed (i.e. have a survey_response as well). Once that's done, you could just filter the unassigned homes by that.

**Comment by LWest001** [comment] 2023-06-23 19:30
That will be useful for some of the other views as well. Will use that when it's available.

**Comment by LWest001** [comment] 2023-06-23 20:57
@mikelynch Would this also apply to a query to `/assignments`? Like, the `homes` object inside of an assignment will get these two attributes?

**Comment by mikelynch** [comment] 2023-06-23 21:10
Yes, see [here](https://github.com/codeforboston/urban-league-heat-pump-accelerator/pull/405/files#diff-c52230901d1f844116a1864bbeee0ba711d8c1642d851fa710bb993abf66bd73R13).

I don't have an example response to hand, but both for homes directly and for the assignment (with the child collection of homes), those attributes will be available.

**Closed** 2023-06-29 19:53 UTC
Labels: Role: App Design and Development
