### ISSUE TITLE
Surveyor view: Feed valid data to Map page when clicking Generate Maps

### ISSUE THREAD

**Issue by LWest001** [codeforboston/urban-league-heat-pump-accelerator#377] opened 2023-05-31 17:09 UTC
![image](https://github.com/codeforboston/urban-league-heat-pump-accelerator/assets/93659375/d7241123-1902-46ec-9a34-1e16c1078a76)

**Comment by mattdelsordo** [comment] 2023-06-21 00:56
Potential duplicate of #295

**Comment by Rando-cal** [comment] 2023-07-16 23:26
Looks good on latest Main

**Closed by Rando-cal** 2023-07-16 23:26 UTC
Labels: Role: App Design and Development
